### Test askBot function### Test GetProductsWithSuppliers chatbot action
POST http://localhost:4004/odata/v4/main/askBot
Content-Type: application/json

{
  "input": "Give me Name, sub category id, Price of HT-1003"
}

####
http://localhost:4004/odata/v4/main/$metadata
